data:
  train_path: data/train.csv   # sửa lại path thực
  dev_path:   data/dev.csv
  test_path:  data/test.csv
  train_conll: data/train.conll

models:
  crf:
    c1: 0.1
    c2: 0.1
    max_iter: 200
  transformer:
    model_name: vinai/phobert-base   # BARTpho … đều được

baselines:
  active: [regex, crf, phobert, punkt, wtp, wtp_finetune]
wtp:
  model_name: wtp-xlmr-c3
  finetune_sentences: 128           # số câu dev để few‑shot

trainer:
  batch_size: 16
  learning_rate: 5e-5
  epochs: 3

output:
  dir: /mnt/data/sentseg_output
